import { useState, useEffect, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import TopBar from "./TopBar";
import ChatPanel from "./ChatPanel";
import AgentPanel from "./AgentPanel";
import CodeEditor from "./CodeEditor";
import PreviewPanel from "./PreviewPanel";
import LogsPanel from "./LogsPanel";
import CostPreviewModal from "./CostPreviewModal";
import { AGENT_STEPS, CODE_BY_PROJECT, CHAT_RESPONSES, MOCK_LOGS, PROJECT_TEMPLATES } from "../data/mockData";

const AGENT_LOGS = {
  planner: [
    "Parsing requirements...",
    "Identifying core features",
    "Architecture plan ready",
  ],
  architect: [
    "Designing component tree",
    "Setting up data models",
    "API contracts defined",
  ],
  coder: [
    "Writing App.tsx",
    "Implementing state management",
    "Styling components",
  ],
  debugger: [
    "Running test suite",
    "0 errors found",
    "Performance optimized",
  ],
};

function detectProjectType(prompt) {
  const p = prompt.toLowerCase();
  if (p.includes("todo") || p.includes("task") || p.includes("list")) return "todo";
  if (p.includes("dashboard") || p.includes("analytics") || p.includes("chart")) return "dashboard";
  if (p.includes("shop") || p.includes("store") || p.includes("commerce") || p.includes("product")) return "ecommerce";
  // cycle based on timestamp
  const types = ["todo", "dashboard", "ecommerce"];
  return types[Math.floor(Date.now() / 10000) % 3];
}

function getProjectName(type) {
  const names = { todo: "task-manager", dashboard: "analytics-dash", ecommerce: "tech-store" };
  return names[type] || "my-app";
}

export default function AppBuilder({ initialPrompt, onReset }) {
  const [selectedModel, setSelectedModel] = useState("gpt-4o");
  const [mode, setMode] = useState("E-1");
  const [credits, setCredits] = useState(1240);
  const [messages, setMessages] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isTyping, setIsTyping] = useState(false);
  const [agentStatuses, setAgentStatuses] = useState({});
  const [agentLogs, setAgentLogs] = useState({});
  const [currentCode, setCurrentCode] = useState("");
  const [projectType, setProjectType] = useState(null);
  const [logsOpen, setLogsOpen] = useState(true);
  const [terminalLogs, setTerminalLogs] = useState([]);
  const [timeElapsed, setTimeElapsed] = useState(0);
  const [estimatedCost, setEstimatedCost] = useState("$0.00");
  const [showCostModal, setShowCostModal] = useState(false);
  const [pendingPrompt, setPendingPrompt] = useState("");
  const [projectName, setProjectName] = useState("untitled-app");
  const [isDeployed, setIsDeployed] = useState(false);

  const timerRef = useRef(null);
  const hasStarted = useRef(false);

  // Start generation flow
  const startGeneration = useCallback((prompt) => {
    const type = detectProjectType(prompt);
    setProjectType(type);
    setProjectName(getProjectName(type));
    setIsGenerating(true);
    setIsTyping(false);
    setCurrentCode("");
    setTerminalLogs([]);
    setAgentStatuses({});
    setAgentLogs({});
    setTimeElapsed(0);
    setEstimatedCost("$0.00");

    // Timer
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setTimeElapsed(t => {
        const next = t + 1;
        const cost = (next * 0.002).toFixed(3);
        setEstimatedCost(`$${cost}`);
        return next;
      });
    }, 1000);

    // Start agent sequence
    runAgentSequence(type, prompt);
  }, []);

  const runAgentSequence = async (type, prompt) => {
    const responses = CHAT_RESPONSES[type] || CHAT_RESPONSES.todo;

    // Add user message
    setMessages(prev => [...prev, { role: "user", content: prompt }]);

    // Step through agents
    for (let i = 0; i < AGENT_STEPS.length; i++) {
      const step = AGENT_STEPS[i];
      await delay(800);

      setAgentStatuses(prev => ({ ...prev, [step.id]: "active" }));

      // Show agent log messages progressively
      const logs = AGENT_LOGS[step.id] || [];
      for (let j = 0; j < logs.length; j++) {
        await delay(600);
        setAgentLogs(prev => ({
          ...prev,
          [step.id]: [...(prev[step.id] || []), logs[j]],
        }));
      }

      // Show assistant chat response for first 2 agents
      if (i < 2 && responses[i]) {
        setIsTyping(true);
        await delay(900);
        setIsTyping(false);
        setMessages(prev => [...prev, { role: "assistant", content: responses[i].content }]);
      }

      await delay(400);
      setAgentStatuses(prev => ({ ...prev, [step.id]: "done" }));
    }

    // Code is being generated by CodeEditor via prop during generation
    setCurrentCode(CODE_BY_PROJECT[type] || CODE_BY_PROJECT.todo);

    // Stream terminal logs
    await delay(500);
    for (let i = 0; i < MOCK_LOGS.length; i++) {
      await delay(120);
      setTerminalLogs(prev => [...prev, MOCK_LOGS[i]]);
    }

    // Final chat message
    await delay(600);
    setIsTyping(true);
    await delay(1000);
    setIsTyping(false);
    if (responses[responses.length - 1]) {
      setMessages(prev => [...prev, responses[responses.length - 1]]);
    }

    // Done
    if (timerRef.current) clearInterval(timerRef.current);
    setIsGenerating(false);
    setCredits(c => c - Math.floor(Math.random() * 15 + 5));
  };

  useEffect(() => {
    if (initialPrompt && !hasStarted.current) {
      hasStarted.current = true;
      setPendingPrompt(initialPrompt);
      setShowCostModal(true);
    }
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [initialPrompt]);

  const handleConfirmGenerate = () => {
    setShowCostModal(false);
    startGeneration(pendingPrompt);
  };

  const handleSendMessage = (msg) => {
    if (isGenerating) return;
    setMessages(prev => [...prev, { role: "user", content: msg }]);
    setIsTyping(true);
    setTimeout(() => {
      setIsTyping(false);
      setMessages(prev => [...prev, {
        role: "assistant",
        content: "Got it! I'll make those changes. Updating the component now...",
      }]);
    }, 1500);
  };

  const handleDeploy = () => {
    setTerminalLogs(prev => [
      ...prev,
      "$ sonar deploy --env=production",
      "Packaging artifacts...",
      "Uploading to edge network...",
      "✓ Deployed to https://my-app.sonar.sh",
      "✓ Live in 1.2s",
    ]);
    setIsDeployed(true);
  };

  const handleReset = () => {
    if (timerRef.current) clearInterval(timerRef.current);
    hasStarted.current = false;
    onReset();
  };

  return (
    <div
      className="flex flex-col overflow-hidden"
      style={{ height: "100vh", background: "#02040A" }}
    >
      {/* Top Bar */}
      <TopBar
        selectedModel={selectedModel}
        setSelectedModel={setSelectedModel}
        mode={mode}
        setMode={setMode}
        isGenerating={isGenerating}
        onDeploy={handleDeploy}
        credits={credits}
        timeElapsed={timeElapsed}
        estimatedCost={estimatedCost}
        projectName={projectName}
      />

      {/* Workspace */}
      <div className="flex flex-1 overflow-hidden">
        {/* LEFT: Chat + Agents */}
        <div
          className="flex flex-col overflow-hidden flex-shrink-0"
          style={{ width: "320px", borderRight: "1px solid rgba(30,41,59,0.7)" }}
        >
          {/* Chat - top 60% */}
          <div className="flex flex-col overflow-hidden" style={{ flex: "1 1 0" }}>
            <ChatPanel
              messages={messages}
              isTyping={isTyping}
              onSendMessage={handleSendMessage}
              projectPrompt={pendingPrompt}
              onReset={handleReset}
            />
          </div>

          {/* Agents - bottom section with fixed height */}
          <div
            className="flex flex-col overflow-hidden flex-shrink-0"
            style={{ height: "320px", borderTop: "1px solid rgba(30,41,59,0.7)" }}
          >
            <AgentPanel agentStatuses={agentStatuses} agentLogs={agentLogs} />
          </div>
        </div>

        {/* CENTER: Editor + Logs */}
        <div className="flex flex-col flex-1 overflow-hidden" style={{ borderRight: "1px solid rgba(30,41,59,0.7)" }}>
          <div className="flex-1 overflow-hidden">
            <CodeEditor
              code={currentCode}
              isGenerating={isGenerating}
              projectType={projectType}
            />
          </div>
          <LogsPanel
            logs={terminalLogs}
            isGenerating={isGenerating}
            isOpen={logsOpen}
            onToggle={() => setLogsOpen(o => !o)}
          />
        </div>

        {/* RIGHT: Preview */}
        <div className="flex-shrink-0 overflow-hidden" style={{ width: "360px" }}>
          <PreviewPanel
            projectType={isGenerating ? null : projectType}
            isGenerating={isGenerating}
          />
        </div>
      </div>

      {/* Cost Preview Modal */}
      <CostPreviewModal
        isOpen={showCostModal}
        onClose={() => { setShowCostModal(false); handleReset(); }}
        onConfirm={handleConfirmGenerate}
        prompt={pendingPrompt}
        selectedModel={selectedModel}
        mode={mode}
      />
    </div>
  );
}

function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
